[package]
name = "contract"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[dependencies.multiversx-sc]
version = "0.40.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.40.0"

[dev-dependencies]
num-bigint = "0.4.2"
