# Credentials holds the list of username-pair pairs that allow access to certain endpoints.
# The password represents the hashed value. In this examples, the password are the hashed usernames.
# Please change these example values as they are just placeholders.
# Example credentials:
# Credentials = [
#      { Username = "example", Password = "hashed password" },
#      { Username = "example2", Password = "hashed password" }
#  ]

[Hasher]
Type = "sha256"
