// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    world
    (
        init => init
        upgrade => upgrade
        fund => fund
        require_positive => require_positive
        get_value => get_value
        get_caller => get_caller
        get_current_block_info => get_current_block_info
        get_prev_block_info => get_prev_block_info
        multiply_by_n => multiply_by_n
        set_n => set_n
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
