# OverridableConfigTomlValues represents an array of items to be overloaded inside other configuration files, which can be helpful
# so that certain config values need to remain the same during upgrades.
# (for example, an Elasticsearch user wants external.toml->ElasticSearchConnector.Enabled to remain true all the time during upgrades, while the default
# configuration of the node has the false value)
# The Path indicates what value to change, while Value represents the new value in string format. The node operator must make sure
# to follow the same type of the original value (ex: uint32: "37", float32: "37.0", bool: "true")
# File represents the file name that holds the configuration. Currently, the supported files are:
# api.toml, config.toml, economics.toml, enableEpochs.toml, enableRounds.toml, external.toml, fullArchiveP2P.toml, p2p.toml, ratings.toml, systemSmartContractsConfig.toml
# -------------------------------
# Un-comment and update the following section in order to enable config values overloading
# -------------------------------
OverridableConfigTomlValues = [
    { File = "config.toml", Path = "VirtualMachine.Execution.WasmVMVersions", Value = [{ StartEpoch = 0, Version = "v1.5" }] },
    { File = "config.toml", Path = "VirtualMachine.Querying.WasmVMVersions", Value = [{ StartEpoch = 0, Version = "v1.5" }] },
    { File = "economics.toml", Path = "FeeSettings.MinGasPrice", Value = "0"},
    { File = "enableEpochs.toml", Path = "EnableEpochs.SCDeployEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.BuiltInFunctionsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RelayedTransactionsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.PenalizedTooMuchGasEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SwitchJailWaitingEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.BelowSignedThresholdEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SwitchHysteresisForMinNodesEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.TransactionSignedWithTxHashEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MetaProtectionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AheadOfTimeGasUsageEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.GasPriceModifierEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RepairCallbackEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.BlockGasAndFeesReCheckEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.BalanceWaitingListsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ReturnDataToLastTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SenderInOutTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.StakeEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.StakingV2EnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DoubleKeyProtectionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.GovernanceEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DelegationManagerEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DelegationSmartContractEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CorrectLastUnjailedEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RelayedTransactionsV2EnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.UnbondTokensV2EnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SaveJailedAlwaysEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ReDelegateBelowMinCheckEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ValidatorToDelegationEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.IncrementSCRNonceInMultiTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTMultiTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.GlobalMintBurnDisableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTTransferRoleEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ComputeRewardCheckpointEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SCRSizeInvariantCheckEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.BackwardCompSaveKeyValueEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTNFTCreateOnMultiShardEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MetaESDTSetEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AddTokensToDelegationEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MultiESDTTransferFixOnCallBackOnEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.OptimizeGasUsedInCrossMiniBlocksEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CorrectFirstQueuedEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DeleteDelegatorAfterClaimRewardsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixOOGReturnCodeEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RemoveNonUpdatedStorageEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.OptimizeNFTStoreEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CreateNFTThroughExecByCallerEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.StopDecreasingValidatorRatingWhenStuckEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FrontRunningProtectionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.IsPayableBySCEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CleanUpInformativeSCRsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.StorageAPICostOptimizationEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.TransformToMultiShardCreateEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTRegisterAndSetAllRolesEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ScheduledMiniBlocksEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CorrectJailedNotUnstakedEmptyQueueEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DoNotReturnOldBlockInBlockchainHookEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AddFailedRelayedTxToInvalidMBsDisableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SCRSizeInvariantOnBuiltInResultEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CheckCorrectTokenIDForTransferRoleEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DisableExecByCallerEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RefactorContextEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FailExecutionOnEveryAPIErrorEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ManagedCryptoAPIsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CheckFunctionArgumentEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CheckExecuteOnReadOnlyEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ESDTMetadataContinuousCleanupEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MiniBlockPartialExecutionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixAsyncCallBackArgsListEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixOldTokenLiquidityEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RuntimeMemStoreLimitEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SetSenderInEeiOutputTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RefactorPeersMiniBlocksEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MaxBlockchainHookCountersEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.WipeSingleNFTLiquidityDecreaseEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AlwaysSaveTokenMetaDataEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RuntimeCodeSizeFixEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.RelayedNonceFixEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SetGuardianEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DeterministicSortOnValidatorsInfoEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.SCProcessorV2EnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AutoBalanceDataTriesEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MigrateDataTrieEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.KeepExecOrderOnCreatedSCRsEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.MultiClaimOnDelegationEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ChangeUsernameEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ConsistentTokensValuesLengthCheckEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixDelegationChangeOwnerOnAccountEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DynamicGasCostForDataTrieStorageLoadEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ScToScLogEventEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.NFTStopCreateEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.ChangeOwnerAddressCrossShardThroughSCEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixGasRemainingForSaveKeyValueBuiltinFunctionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CurrentRandomnessOnSortingEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.AlwaysMergeContextsInEEIEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.UseGasBoundedShouldFailExecutionEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.DynamicESDTEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.EGLDInMultiTransferEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.CryptoOpcodesV2EnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.UnJailCleanupEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixRelayedBaseCostEnableEpoch", Value = 0 },
    { File = "enableEpochs.toml", Path = "EnableEpochs.FixRelayedMoveBalanceToNonPayableSCEnableEpoch", Value = 0 },
]
