name: "Setup Node.js with pnpm and cache"

inputs:
  node-version:
    description: "Node.js version to use."
  node-registry-url:
    description: "Optional registry to set up for auth."
  pnpm-version:
    description: "pnpm version to use."
  skip-install:
    description: "Skip the installation step."
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.node-registry-url }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
      if: ${{ inputs.skip-install == 'false' }}
