// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data
    (
        init => init
        upgrade => upgrade
        value_set => value_set
        vec_push => vec_push
        unordered_set_insert => unordered_set_insert
        set_insert => set_insert
        map_insert => map_insert
        user_create => user_create
        esdt_local_mint => esdt_local_mint
        esdt_nft_create => esdt_nft_create
        esdt_nft_create_compact => esdt_nft_create_compact
        direct_send => direct_send
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
