// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data
    (
        init => init
        single_add => single_add
        single_remove => single_remove
        unordered_set_add => unordered_set_add
        unordered_set_remove => unordered_set_remove
        set_add => set_add
        set_remove => set_remove
        map_add => map_add
        map_remove => map_remove
        vec_add => vec_add
        vec_remove => vec_remove
        user_add => user_add
        esdt_local_mint => esdt_local_mint
        esdt_nft_create => esdt_nft_create
        esdt_nft_create_compact => esdt_nft_create_compact
        direct_send => direct_send
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
