name: Main

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 20
          pnpm-version: 9

      - name: Lint
        run: pnpm lint

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: xsuite-lightsimulnet/src/go.sum

      - name: Build xsuite-lightsimulnet
        run: pnpm build-xsuite-lightsimulnet

      - name: Build xsuite
        run: pnpm build-xsuite

      - name: Add xSuite Rust key in env
        run: echo "XSUITE_RUST=$(pnpm xsuite install-rust-key)" >> $GITHUB_ENV

      - name: Cache Rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ env.XSUITE_RUST }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Install Rust
        run: pnpm xsuite install-rust

      - name: Test xsuite
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          pnpm test-xsuite

      - name: Verify xsuite wasms
        run: pnpm verify-xsuite-wasms

      - name: Build contracts
        run: pnpm build-contracts

      - name: Typecheck contracts
        run: pnpm typecheck-contracts

      - name: Test contracts
        run: pnpm test-contracts
