name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          pnpm-version: 8

      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup
          restore-keys: ${{ runner.os }}-rustup

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('contracts/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Cache Rust target folder
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target
          restore-keys: ${{ runner.os }}-target

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: xsuite-fproxy/src/go.sum

      - name: Lint
        run: pnpm lint

      - name: Build xsuite-fproxy
        run: pnpm build-xsuite-fproxy

      - name: Build xsuite
        run: pnpm build-xsuite

      - name: Test xsuite
        run: pnpm test-xsuite

      - name: Build xsuite-cli
        run: pnpm build-xsuite-cli

      - name: Test xsuite-cli
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          pnpm test-xsuite-cli

      - name: Install Rust
        run: pnpm xsuite install-rust

      - name: Verify xsuite wasms
        run: pnpm verify-xsuite-wasms

      - name: Build contracts
        run: pnpm build-contracts

      - name: Typecheck contracts
        run: pnpm typecheck-contracts

      - name: Test contracts
        run: pnpm test-contracts
