name: Main

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          pnpm-version: 8

      - name: Cache Rust setup
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('xsuite/src/cli/rustSettings.ts') }}-${{ hashFiles('contracts/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Cache Rust target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('contracts/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-target-

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: xsuite-simulnet/src/go.sum

      - name: Lint
        run: pnpm lint

      - name: Build xsuite-simulnet
        run: pnpm build-xsuite-simulnet

      - name: Build xsuite
        run: pnpm build-xsuite

      - name: Test xsuite
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          pnpm test-xsuite

      - name: Install Rust
        run: pnpm xsuite install-rust

      - name: Verify xsuite wasms
        run: pnpm verify-xsuite-wasms

      - name: Build contracts
        run: pnpm build-contracts

      - name: Typecheck contracts
        run: pnpm typecheck-contracts

      - name: Test contracts
        run: pnpm test-contracts
