name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        go-version: [1.19.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Cache Rust toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup
          restore-keys: |
            ${{ runner.os }}-rustup

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('contracts/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Rust target folders
        uses: actions/cache@v2
        with:
          path: contracts/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('contracts/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build xSuite
        run: pnpm build-xsuite

      - name: Test xSuite
        run: pnpm test-xsuite

      - name: Build xSuite-cli
        run: pnpm build-xsuite-cli

      - name: xSuite setup Rust
        run: pnpm xsuite setup-rust

      - name: xSuite build contracts
        run: pnpm build-contracts

      - name: Typecheck contracts
        run: pnpm typecheck-contracts

      - name: Test contracts
        run: pnpm test-contracts
