name: Release xsuite-cli

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          node-registry-url: "https://registry.npmjs.org"
          pnpm-version: 8

      - name: Build xsuite-cli
        run: pnpm build-xsuite && pnpm build-xsuite-cli

      - name: Publish xsuite-cli to NPM
        run: git config core.fileMode false && cd xsuite-cli && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
