name: Release xsuite-chainsimulator

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          pnpm-version: 8

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache-dependency-path: xsuite-chainsimulator/mx-chain-simulator-go/go.sum

      - name: Build xsuite-chainsimulator
        run: pnpm build-xsuite-chainsimulator

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: xsuite-chainsimulator/bin

  test:
    needs: build

    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            binary: csproxy-linux-amd64
          - os: macos-12
            binary: csproxy-darwin-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package
          path: xsuite-chainsimulator/bin

      - name: Add execute permissions
        run: chmod +x xsuite-chainsimulator/bin/csproxy-*

      - name: Test
        run: |
          ./xsuite-chainsimulator/bin/${{ matrix.binary }} --config xsuite-chainsimulator/config/config.toml --node-configs xsuite-chainsimulator/config/node/config --proxy-configs xsuite-chainsimulator/config/proxy/config &
          SERVER_PID=$!
          sleep 2
          if kill -0 $SERVER_PID 2>/dev/null; then
            echo "Chainsimulator succeeded to start."
            kill $SERVER_PID
            wait $SERVER_PID || [ $? -eq 143 ]
          else
            echo "Chainsimulator failed to start."
            exit 1
          fi

  publish:
    needs: test

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package
          path: xsuite-chainsimulator/bin

      - name: Add execute permissions
        run: chmod +x xsuite-chainsimulator/bin/csproxy-*

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          node-registry-url: "https://registry.npmjs.org"
          pnpm-version: 8
          skip-install: true

      - name: Publish xsuite-chainsimulator to NPM
        run: git config core.fileMode false && cd xsuite-chainsimulator && pnpm publish --publish-branch dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
