name: Release xSuite

on:
  workflow_dispatch:

jobs:
  build-on-macOS:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18.x
          pnpm-version: 8

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
          cache-dependency-path: xsuite/fproxy/go.sum

      - name: Build xSuite
        run: pnpm build-fproxy-${{ runner.os }} && pnpm build-xsuite

      - name: Test xSuite
        run: pnpm test-xsuite

      - name: Upload fproxy
        uses: actions/upload-artifact@v3
        with:
          name: fproxy
          path: xsuite/fproxy/fproxy-*

  build-on-Linux-and-publish:
    needs: build-on-macOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download fproxy
        uses: actions/download-artifact@v3
        with:
          name: fproxy
          path: xsuite/fproxy

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
          pnpm-version: 8

      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
          cache-dependency-path: xsuite/fproxy/go.sum

      - name: Build xSuite
        run: pnpm build-fproxy-${{ runner.os }} && pnpm build-xsuite

      - name: Test xSuite
        run: pnpm test-xsuite

      - name: Publish xSuite to NPM
        run: git config core.fileMode false && cd xsuite && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
