name: Release xsuite-lightsimulnet

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
          cache-dependency-path: xsuite-lightsimulnet/src/go.sum

      - name: Build xsuite-lightsimulnet
        run: pnpm build-xsuite-lightsimulnet

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: xsuite-lightsimulnet/bin

  test:
    needs: build

    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            binary: lsproxy-linux-amd64
          - os: macos-12
            binary: lsproxy-darwin-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: package
          path: xsuite-lightsimulnet/bin

      - name: Add execute permissions
        run: chmod +x xsuite-lightsimulnet/bin/lsproxy-*

      - name: Test
        run: |
          ./xsuite-lightsimulnet/bin/${{ matrix.binary }} &
          SERVER_PID=$!
          sleep 2
          if kill -0 $SERVER_PID 2>/dev/null; then
            echo "Simulnet succeeded to start."
            kill $SERVER_PID
            wait $SERVER_PID || [ $? -eq 143 ]
          else
            echo "Simulnet failed to start."
            exit 1
          fi

  publish:
    needs: test

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: package
          path: xsuite-lightsimulnet/bin

      - name: Add execute permissions
        run: chmod +x xsuite-lightsimulnet/bin/lsproxy-*

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-registry-url: "https://registry.npmjs.org"
          skip-install: true

      - name: Publish xsuite-lightsimulnet to NPM
        run: git config core.fileMode false && cd xsuite-lightsimulnet && pnpm publish --publish-branch dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
