name: Release xsuite

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18
          node-registry-url: "https://registry.npmjs.org"
          pnpm-version: 8

      - name: Build xsuite
        run: pnpm build-xsuite

      - name: Publish xsuite to NPM
        run: git config core.fileMode false && cd xsuite && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
