name: Release xSuite-cli

on:
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-version: 18.x
          node-registry-url: "https://registry.npmjs.org"
          pnpm-version: 8

      - name: Build xSuite-cli
        run: pnpm build-xsuite-cli

      - name: Typecheck xSuite-cli
        run: pnpm typecheck-xsuite-cli

      - name: Publish xSuite-cli to NPM
        run: git config core.fileMode false && cd xsuite-cli && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
