name: Release xsuite-lightsimulnet

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
          cache-dependency-path: xsuite-lightsimulnet/src/go.sum

      - name: Build xsuite-lightsimulnet
        run: pnpm build-xsuite-lightsimulnet

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: |
            xsuite-lightsimulnet-darwin-amd64/bin/lsproxy
            xsuite-lightsimulnet-linux-amd64/bin/lsproxy

  test:
    needs: build

    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          merge-multiple: true

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
      
      - name: Test
        run: pnpm test-xsuite-lightsimulnet

  publish:
    needs: test

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          merge-multiple: true

      - name: Use Node.js & pnpm
        uses: ./.github/actions/node-pnpm
        with:
          node-registry-url: "https://registry.npmjs.org"

      - name: Publish xsuite-lightsimulnet packages to NPM
        run: git config core.fileMode false && pnpm --filter "@xsuite/light-simulnet*" publish --publish-branch dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
